### PR TITLE
Angular 13 update

### PR DESCRIPTION
**Pull request by Trombach**
This PR updates Angular and Angular Material to version 13.

I've also included a few `npm audit` fixes.

### CODE REVIEW

**Comment by Trombach** [comment]
Some packages complain about depencencies:

image

**Comment by rosemcc** [comment]
> 

I didn't see the same warnings come up when I installed. Maybe it's ok since you did the npm audit fix? If they come up again we can try installing the deps.

**Review by rosemcc — APPROVED** [review]
Looks good!

**Comment by Trombach** [comment]
> > 
> 
> I didn't see the same warnings come up when I installed. Maybe it's ok since you did the npm audit fix? If they come up again we can try installing the deps.

That's good to know. I didn't see any issues either despite these warnings.

**Pull request merged**
