### PR TITLE
SSO Checking

### PR DESCRIPTION
**Pull request by JuliusKarl**
When content is SSO Protected, check if the user is authenticated.

### CODE REVIEW

**Comment by rosemcc** [comment]
I don't know if this is a new problem, but say you go to a protected page, it logs you in all good, but then if you try to go back to whatever page you were on before that protected page you get an error - either a bad request page, or that generic uni page that says 'you shouldn't bookmark this login page'.. so perhaps there is some router cleanup that should be done if the user had to login on their way to a protected page... ? not something that needs to be fixed immediately, just noting it down here.

**Comment by JuliusKarl** [comment]
> I don't know if this is a new problem, but say you go to a protected page, it logs you in all good, but then if you try to go back to whatever page you were on before that protected page you get an error - either a bad request page, or that generic uni page that says 'you shouldn't bookmark this login page'.. so perhaps there is some router cleanup that should be done if the user had to login on their way to a protected page... ? not something that needs to be fixed immediately, just noting it down here.

hmm i'm not using any manual `router.navigate` only the loginService.doLogin('${route here}')

**Comment by rosemcc** [comment]
Unit tests seem to be failing, but is that fixed somewhere else?

**Comment by rosemcc** [comment]
Hey @uoa-noel , just want to get you to have a quick look at this SSO check stuff - does it make sense to you to do it that way? It kind of ties in with the typename stuff because its about how our Apollo errors are handled. The changes here are a way to avoid the unauthenticated error happening in the first place. But whether it makes sense to do it this way, or just let the error happen then redirect the user to login, I'm not super sure about. Let me know your thoughts :)

**Comment by rosemcc** [comment]
Close for now. SSO checks should be handled in app.module. Reopen if changes required.

**Pull request closed without merging**
