### PR TITLE
Jenkins notification hotfix

### PR DESCRIPTION
**Pull request by warrickct**
* Re-adding slack notification that was deleted in the browserstack Jenkins stage.

* Added example env variables for 2FAb Lambda

* Added even longer error message for situations where grabbing OAuth tokens fail.

### CODE REVIEW

**Review by Hganavak — CHANGES_REQUESTED** [review]
Don't understand why you're doing this as an extra stage, and not just using the `post {` stage's built in `success {` like we were doing before? 😕

**Comment by warrickct** [comment]
I think the build success message was placed like this beforehand f2110c69d97ab9d5ae0953a843f53ad67068f91f. I just moved it back to where it was originally.

**Comment by warrickct** [comment]
I guess it was like that before due to browserstack failures preventing success message? Could move it into the post stage if you want.

**Comment by Hganavak** [comment]
Yup, it was because of BrowserStack tests, can throw it back in `post { success {` again :v:

**Comment by warrickct** [comment]
* Added example env variables for 2FAb Lambda
* Added even longer error message for situations where grabbing OAuth tokens fail.
* Moved Slack message success notification to `post` stage.

**Comment by Hganavak** [comment]
Closing this PR as it conflicts with `master`, contains some stuff not related to the PR, and has been solved in #49.

**Pull request closed without merging**
