### PR TITLE
Subhub Page

### PR DESCRIPTION
**Pull request by JuliusKarl**
Creating SubHub Pages

- Refactor SubHub UI
- Refactor SubHub Queries
- SubHub View Switching

### CODE REVIEW

**Review by warrickct — COMMENTED** [review]
Subhubs look good and everything else is looking all good for the most part. Just a couple things:
* Some of the e2e tests are failing. Seems like it's due to a change in the routes. Perhaps they should be altered to match or possibly omit if routing is still under development.
* Not related to the subhub page but I noticed there's a width scroller on the body content for articles. 
width_scroll_nesi_article

Other than those minor things it seems good to me. Might be worth waiting for Sam's input regarding the e2e tests before merging.

**Comment by JuliusKarl** [comment]
Changes

- The code became messy so I re-branched from current master and added the changes to subhub-page _(includes graphql updates)_
- I've encountered the width scroller before but now I can't find it even using different screens and resolutions, let me know if and how you find it again
- I tried to fix the e2e tests but for some reason dynamic routing isn't working for first-level sububs e.g. /cer but it works for child subhubs e.g. /cer/our-services

**Review by uoa-noel — COMMENTED** [review]
New design looks quite nice and fresh, well done! Just couple of notes:
* A couple of styling is added inline rather than in the CSS file - could look at moving them to a CSS file.
* Seems like there are vertical scrollbars. If you go to /star-wars/star-wars-lore/who-are-the-jedi and scroll to the end of text, there seems to be a vertical scrollbar.
image
* Probably not related to your changes, but when I'm on a Subhub page, the browser back/forward buttons seem to not work properly - it seems to go "back" to another part of the page, and the forward button doesn't show anything.

Otherwise looks good! :100:  I like that you have comments on top of styling to describe what they're for, will have to steal that for my code.

**Comment by JuliusKarl** [comment]
Fixed

- Extract styling from HTML and put into SCSS
- Back/Forward Navigation

Unfixed

- I can't seem to replicate the bottom scroller (although I have seen it in the past). Do you know what your screen settings are? I'm the only one not seeing it

**Comment by uoa-noel** [comment]
The banner has a few CSS rules for `min-width: 100vw;` . The `vw` css unit takes any vertical scrollbar width into account, so 100vw is width of the viewport inclusive of the scrollbar width. This means the banner doesn't fit on a page longer than the viewport and causes overflow. I think on macos safari doesn't display a scrollbar so this problem doesn't occur there, but occurs on Windows and Linux.

**Review by uoa-noel — COMMENTED** [review]
Good stuff! I think it's now ready to merge.

**Pull request closed without merging**
