### PR TITLE
Event Page

### PR DESCRIPTION
**Pull request by JuliusKarl**

### CODE REVIEW

**Comment by rosemcc** [comment]
Hey Julius this is looking really good. There might be a few more bits to add from looking at the content model, for example location and/or address of the event isn't handled. Icon as well. But we still need to have the design meeting to refine the page layouts anyway. 

Couple of issues to note:
There is an issue in the toolbar in mobile view (around <425px) the toolbar icons on the right hand side get messed up
image

Unit tests are passing but seem to have a lot of warnings/errors being generated like 'ERROR: 'Error loading all SubHub:', TypeError: Cannot read property 'use' of undefined'

**Comment by JuliusKarl** [comment]
Awesome
- Location/Address can be simply added once defined in meeting
- Navbar scaling is fixed in `front-page` branch
- I've been getting `'ERROR: 'Error loading all SubHub:', TypeError: Cannot read property 'use' of undefined'` since I can remember but it doesn't seem to break anything

**Comment by rosemcc** [comment]
Great, yeah karma seems to throw up a lot of random errors. Ok to merge when you're ready

**Comment by rosemcc** [comment]
Nice work Julius, you can merge

**Pull request merged**
